title: "Hugging Face KREW"
email: heuristicwave@gmail.com
timezone: Asia/Seoul
baseurl: 
permalink: "/:title/"
logo: 'assets/images/hfkr_logo.png'
favicon: 'assets/images/favicon.ico'
author: Admin
paginate: 30
disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  math_engine: katex
  input: GFM
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# # Enable displaying posts with future dates
future: true

# Authors
authors:
  admin:
    name: HFKR Team
    display_name: Admin
    avatar: 'assets/images/logo.png'
    email: wowthemesnet@gmail.com
    web: https://hugging-face-krew.github.io/
    description: "Hugging Face KREW Team"
  chaewon:
    name: Song Chaewon
    display_name: Chaewon 
    avatar: 'assets/images/author/chaewon.png'
    email: chaewon1019@ewhain.net 
    web: https://github.com/chhaewxn/
    description: "Hello! I'm Chaewon Song, a developer aspiring to become an Software engineer ðŸ¤—"
  minju:
    name: Jwa Minju
    display_name: minju 
    avatar: 'assets/images/author/minju.png'
    email: jminj6@gmail.com 
    web: https://github.com/Jwaminju/
    description: "Hello, I'm minju! ðŸ¤—"

# Social
social:
  instagram: https://www.instagram.com/bootstrapstarter/
  facebook: https://www.facebook.com/bootstrapstartercom-346329609045284
  twitter: https://twitter.com/bstartercom

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
